import './style.css';
import { getUser, handleAuthCallback, onAuthChange } from '@netlify/identity';

const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const clean = (value = '') => String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]);
const formatMoney = (value) => new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP', maximumFractionDigits: 0 }).format(Number(value) || 0);
const formatDate = (value, year = true) => value ? new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'short', ...(year ? { year: 'numeric' } : {}) }).format(new Date(`${value}${String(value).length === 10 ? 'T12:00:00' : ''}`)) : 'Not confirmed';
const demo = { opportunities: [{ id: 'demo-1', funder_name: 'National Lottery Community Fund', programme_name: 'Awards for All', deadline: '2026-10-18', amount_max: 20000, score: 82, status: 'go', summary: 'Community-led creative programme supporting underrepresented young people.', score_breakdown: { strategic_fit: 18, eligibility: 17, evidence: 16, capacity: 15, return: 16 } }, { id: 'demo-2', funder_name: 'Arts Council England', programme_name: 'National Lottery Project Grants', deadline: '2026-11-12', amount_max: 30000, score: 64, status: 'review', summary: 'Creative development and public engagement programme.', score_breakdown: { strategic_fit: 15, eligibility: 12, evidence: 13, capacity: 11, return: 13 } }, { id: 'demo-3', funder_name: 'Paul Hamlyn Foundation', programme_name: 'Arts-based Learning Fund', deadline: null, amount_max: 90000, score: 41, status: 'researching', summary: 'Longer-term evidence-led learning programme.', score_breakdown: { strategic_fit: 12, eligibility: 9, evidence: 8, capacity: 6, return: 6 } }], projects: [], evidence: [], files: [], assignments: [], activity: [] };

const state = { data: { opportunities: [], projects: [], evidence: [], files: [], assignments: [], activity: [] }, user: null, tab: 'projects', selected: null, preview: ['localhost', '127.0.0.1'].includes(location.hostname) };

function toast(message, error = false) { const notice = $('#notice'); notice.textContent = message; notice.className = `notice${error ? ' error' : ''}`; notice.hidden = false; window.clearTimeout(toast.timer); toast.timer = window.setTimeout(() => { notice.hidden = true; }, 8000); }

async function api(path, options = {}) {
  const response = await fetch(`/api${path}`, { credentials: 'same-origin', ...options, headers: { ...(options.body ? { 'content-type': 'application/json' } : {}), ...(options.headers || {}) } });
  if (!response.ok) { const payload = await response.json().catch(() => ({ message: `Request failed (${response.status})` })); const error = new Error(payload.message); error.status = response.status; error.details = payload.details; error.requestId = payload.requestId; throw error; }
  return response.headers.get('content-type')?.includes('application/json') ? response.json() : response.blob();
}

function describeError(error) { return `${error.message}${error.requestId ? ` Reference: ${error.requestId}` : ''}${error.details?.length ? ` ${error.details.map((item) => item.action).join(' ')}` : ''}`; }

function showView(name) {
  $$('.view').forEach((view) => view.classList.toggle('active', view.id === name));
  $$('.nav-item').forEach((button) => button.classList.toggle('active', button.dataset.view === name));
  const labels = { overview: ['FUNDING OPERATIONS', 'Funding overview'], pipeline: ['OPPORTUNITY PIPELINE', 'Opportunities'], research: ['CURRENT INTELLIGENCE', 'Live research'], library: ['REUSABLE KNOWLEDGE', 'Project library'], activity: ['ACCOUNTABILITY', 'Activity log'] };
  $('#section-kicker').textContent = labels[name][0]; $('#section-title').textContent = labels[name][1]; location.hash = name; $('#rail').classList.remove('open');
}

function statusPill(status) { return `<span class="pill ${clean(status)}">${clean(status.replace('_', ' '))}</span>`; }

function renderOverview() {
  const opportunities = state.data.opportunities; const active = opportunities.filter((item) => !['no_go','submitted','won','lost'].includes(item.status)); const upcoming = opportunities.filter((item) => item.deadline && new Date(item.deadline) >= new Date()).sort((a, b) => new Date(a.deadline) - new Date(b.deadline)); const next = upcoming[0];
  $('#nav-count').textContent = opportunities.length; $('#metric-active').textContent = active.length; $('#metric-go').textContent = opportunities.filter((item) => item.status === 'go').length; $('#metric-value').textContent = formatMoney(opportunities.reduce((sum, item) => sum + Number(item.amount_max || 0), 0)); $('#metric-deadline').textContent = next ? formatDate(next.deadline, false) : '—'; $('#metric-deadline-label').textContent = next?.programme_name || 'Nothing scheduled';
  $('#priority-list').innerHTML = opportunities.slice().sort((a, b) => b.score - a.score).slice(0, 5).map((item) => `<div class="list-row"><button data-opportunity="${item.id}"><strong>${clean(item.programme_name)}</strong><small>${clean(item.funder_name)}</small></button><div class="score-ring" style="--score:${item.score}"><span>${item.score}</span></div><div>${statusPill(item.status)}</div><small>${formatDate(item.deadline, false)}</small></div>`).join('') || '<div class="empty-state">No opportunities yet. Add your first funding lead.</div>';
  $('#deadline-watch').innerHTML = upcoming.slice(0, 4).map((item) => { const date = new Date(`${item.deadline}T12:00:00`); return `<div class="deadline-row"><div class="date-tile"><span>${date.toLocaleString('en-GB', { month: 'short' }).toUpperCase()}</span>${date.getDate()}</div><div><strong>${clean(item.programme_name)}</strong><br><small>${clean(item.funder_name)}</small></div></div>`; }).join('') || '<div class="empty-state">No upcoming deadlines.</div>';
}

function renderPipeline() {
  const term = $('#opportunity-search').value.toLowerCase(); const status = $('#status-filter').value; const opportunities = state.data.opportunities.filter((item) => (!term || `${item.funder_name} ${item.programme_name}`.toLowerCase().includes(term)) && (!status || item.status === status));
  $('#opportunity-table').innerHTML = `<div class="table-head"><span>Opportunity</span><span>Deadline</span><span>Maximum</span><span>Score</span><span>Stage</span></div>${opportunities.map((item) => `<div class="table-row"><button data-opportunity="${item.id}">${clean(item.programme_name)}<small>${clean(item.funder_name)}</small></button><span>${formatDate(item.deadline)}</span><span>${formatMoney(item.amount_max)}</span><strong>${item.score}/100</strong><span>${statusPill(item.status)}</span></div>`).join('') || '<div class="empty-state">No opportunities match this view.</div>'}`;
  $('#research-opportunity').innerHTML = `<option value="">Do not attach to an opportunity</option>${state.data.opportunities.map((item) => `<option value="${item.id}">${clean(item.programme_name)} — ${clean(item.funder_name)}</option>`).join('')}`;
}

function renderLibrary() {
  $('#project-count').textContent = state.data.projects.length; $('#evidence-count').textContent = state.data.evidence.length; $('#file-count').textContent = state.data.files.length; const items = state.data[state.tab] || [];
  $('#library-grid').innerHTML = items.map((item) => { if (state.tab === 'files') return `<article class="library-item"><p class="kicker">${clean(item.category)}</p><h3>${clean(item.filename)}</h3><p>${Math.max(1, Math.round(item.size_bytes / 1024))} KB · ${clean(item.content_type)}</p><footer><span>Uploaded ${formatDate(item.created_at)}</span><a href="/api/files/${item.id}">Download ↓</a></footer></article>`; return `<article class="library-item"><p class="kicker">${clean(item.evidence_type || item.geography || 'PROJECT')}</p><h3>${clean(item.name || item.title)}</h3><p>${clean((item.description || item.content || 'No description yet.').slice(0, 220))}</p><footer><span>Updated ${formatDate(item.updated_at)}</span><span>${clean(item.created_by || '')}</span></footer></article>`; }).join('') || `<div class="empty-state">No ${state.tab} yet.</div>`;
}

function renderActivity() { $('#activity-list').innerHTML = state.data.activity.map((item) => `<div class="activity-row"><small>${formatDate(item.created_at)}</small><span><strong>${clean(item.actor_email)}</strong> ${clean(item.action)}d ${clean(item.entity_type)}</span>${statusPill(item.actor_role)}</div>`).join('') || '<div class="empty-state">No changes have been recorded yet.</div>'; }
function renderAll() { renderOverview(); renderPipeline(); renderLibrary(); renderActivity(); bindOpportunityButtons(); }

function bindOpportunityButtons() { $$('[data-opportunity]').forEach((button) => { button.onclick = () => openOpportunity(button.dataset.opportunity); }); }

function openOpportunity(id) {
  const opportunity = state.data.opportunities.find((item) => item.id === id); if (!opportunity) return; state.selected = opportunity; const scores = opportunity.score_breakdown || {};
  $('#drawer-content').innerHTML = `<p class="kicker">${clean(opportunity.funder_name)}</p><h2>${clean(opportunity.programme_name)}</h2><p>${statusPill(opportunity.status)} &nbsp; <strong>${opportunity.score}/100</strong></p><p>${clean(opportunity.summary || 'No summary yet.')}</p><div class="drawer-section"><h3>DECISION</h3><select id="drawer-status"><option value="researching">Researching</option><option value="review">Review</option><option value="go">Go</option><option value="no_go">No-go</option><option value="drafting">Drafting</option><option value="submitted">Submitted</option><option value="won">Won</option><option value="lost">Lost</option></select><div class="score-fields">${[['strategic_fit','Strategic fit'],['eligibility','Eligibility'],['evidence','Evidence strength'],['capacity','Delivery capacity'],['return','Return on effort']].map(([key,label]) => `<label>${label}<input type="number" min="0" max="20" data-score="${key}" value="${Number(scores[key] || 0)}" /></label>`).join('')}</div><button class="primary" id="save-decision">Save score & decision</button></div><div class="drawer-section"><h3>ASSIGN WORK</h3><div class="assignment-grid"><input type="email" id="assign-email" placeholder="Assignee email" /><input id="assign-task" placeholder="Task, e.g. Draft need statement" /><input type="date" id="assign-due" /><button class="secondary" id="save-assignment">Assign & notify</button></div></div><div class="drawer-section"><h3>RESEARCH</h3><p>${clean((opportunity.research_notes || 'No saved research yet.').slice(0, 500))}</p><small>Last checked: ${formatDate(opportunity.last_checked_at)}</small></div><div class="drawer-actions"><button class="secondary" data-export="docx">Export Word</button><button class="secondary" data-export="pdf">Export PDF</button><button class="secondary" id="research-this">Research this funder</button></div>`;
  $('#drawer-status').value = opportunity.status; $('#opportunity-drawer').classList.add('open'); $('#opportunity-drawer').setAttribute('aria-hidden', 'false'); $('#scrim').classList.add('open');
  $('#save-decision').onclick = saveDecision; $('#save-assignment').onclick = saveAssignment; $('#research-this').onclick = () => { closeDrawer(); $('#research-question').value = `Research current eligibility, award range, deadline and strategic fit for ${opportunity.funder_name} — ${opportunity.programme_name}.`; $('#research-opportunity').value = opportunity.id; showView('research'); }; $$('[data-export]', $('#drawer-content')).forEach((button) => { button.onclick = () => download(`/export/${opportunity.id}/${button.dataset.export}`); });
}

function closeDrawer() { $('#opportunity-drawer').classList.remove('open'); $('#opportunity-drawer').setAttribute('aria-hidden', 'true'); $('#scrim').classList.remove('open'); }

async function saveDecision() { const breakdown = Object.fromEntries($$('[data-score]', $('#drawer-content')).map((input) => [input.dataset.score, Number(input.value)])); try { await api(`/opportunities/${state.selected.id}`, { method: 'PATCH', body: JSON.stringify({ status: $('#drawer-status').value, score_breakdown: breakdown }) }); toast('Decision and score saved.'); await loadData(); openOpportunity(state.selected.id); } catch (error) { toast(describeError(error), true); } }

async function saveAssignment() { try { const result = await api('/assignments', { method: 'POST', body: JSON.stringify({ opportunity_id: state.selected.id, assignee_email: $('#assign-email').value, task: $('#assign-task').value, due_at: $('#assign-due').value || null }) }); toast(result.email.sent ? 'Assignment saved and email sent.' : 'Assignment saved. Email alerts are not configured.'); await loadData(); } catch (error) { toast(describeError(error), true); } }

async function download(path) { try { const blob = await api(path); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = ''; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 2000); } catch (error) { toast(describeError(error), true); } }

const forms = {
  opportunity: { title: 'Add opportunity', endpoint: '/opportunities', fields: [['funder_name','Funder','text'],['programme_name','Programme','text'],['url','Official URL','url'],['deadline','Deadline','date'],['amount_min','Minimum award (£)','number'],['amount_max','Maximum award (£)','number'],['summary','What makes this relevant?','textarea']] },
  project: { title: 'Add project', endpoint: '/projects', fields: [['name','Project name','text'],['geography','Geography','text'],['budget_total','Total budget (£)','number'],['description','Project description','textarea'],['beneficiaries','Who benefits?','textarea']] },
  evidence: { title: 'Add evidence', endpoint: '/evidence', fields: [['title','Evidence title','text'],['evidence_type','Evidence type','select'],['occurred_on','Evidence date','date'],['source_url','Source URL','url'],['content','Evidence or finding','textarea']] },
};

function openForm(kind) { const form = forms[kind]; $('#record-form').dataset.kind = kind; $('#form-title').textContent = form.title; $('#form-kicker').textContent = kind === 'opportunity' ? 'NEW FUNDING LEAD' : 'LIBRARY RECORD'; $('#form-fields').innerHTML = form.fields.map(([name,label,type]) => `<div class="field"><label for="field-${name}">${label}</label>${type === 'textarea' ? `<textarea id="field-${name}" name="${name}"></textarea>` : type === 'select' ? `<select id="field-${name}" name="${name}"><option value="note">Note</option><option value="statistic">Statistic</option><option value="testimonial">Testimonial</option><option value="evaluation">Evaluation</option><option value="case_study">Case study</option></select>` : `<input id="field-${name}" name="${name}" type="${type}" ${['funder_name','programme_name','name','title'].includes(name) ? 'required' : ''} />`}</div>`).join(''); $('#form-dialog').showModal(); }

async function loadData() { try { state.data = await api('/dashboard'); renderAll(); } catch (error) { if (state.preview) { state.data = demo; renderAll(); return; } if (error.status === 401) $('#login-dialog').showModal(); else toast(describeError(error), true); } }

async function boot() {
  if (state.preview) { state.data = demo; state.user = { email: 'preview@weareunedited.com', role: 'owner', name: 'Preview' }; renderAll(); $('#system-state').classList.add('good'); $('#system-state').innerHTML = '<i></i>Preview mode'; return; }
  try { await handleAuthCallback(); } catch (error) { toast(error.message, true); }
  try { const health = await api('/health'); $('#system-state').classList.toggle('good', health.database); $('#system-state').innerHTML = `<i></i>${health.database ? 'Core ready' : 'Database setup needed'}`; } catch { $('#system-state').innerHTML = '<i></i>Setup needed'; }
  try { const response = await api('/me'); state.user = response.user; const names = state.user.name.split(/\s+/); $('#profile-initials').textContent = names.map((part) => part[0]).join('').slice(0,2).toUpperCase(); $('#profile-name').textContent = state.user.name; $('#profile-role').textContent = state.user.role; await loadData(); } catch (error) { if (error.status === 401) $('#login-dialog').showModal(); else toast(describeError(error), true); }
}

function registerWebMCP() {
  if (!document.modelContext?.registerTool) return;
  try { document.modelContext.registerTool({ name: 'start_funding_research', title: 'Start funding research', description: 'Open the live funding research workspace and prepare a specific research question. This does not run or save research.', inputSchema: { type: 'object', properties: { question: { type: 'string' } }, required: ['question'], additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: false }, execute({ question }) { if (typeof question !== 'string' || !question.trim()) throw new Error('question is required'); showView('research'); $('#research-question').value = question.trim(); return { prepared: true, view: 'research' }; } }); } catch (error) { console.warn('WebMCP registration unavailable', error); }
}

$$('[data-view]').forEach((button) => { button.addEventListener('click', () => showView(button.dataset.view)); }); $$('[data-create]').forEach((button) => { button.addEventListener('click', () => openForm(button.dataset.create)); }); $$('[data-close-dialog]').forEach((button) => { button.onclick = () => button.closest('dialog').close(); });
$('#menu-button').onclick = () => $('#rail').classList.toggle('open'); $('#drawer-close').onclick = closeDrawer; $('#scrim').onclick = closeDrawer; $('#quick-research').onclick = () => showView('research'); $('#opportunity-search').oninput = () => { renderPipeline(); bindOpportunityButtons(); }; $('#status-filter').onchange = () => { renderPipeline(); bindOpportunityButtons(); };
$$('[data-tab]').forEach((button) => { button.onclick = () => { state.tab = button.dataset.tab; $$('[data-tab]').forEach((item) => item.classList.toggle('active', item === button)); renderLibrary(); }; });
$('#record-form').addEventListener('submit', async (event) => { event.preventDefault(); const kind = event.currentTarget.dataset.kind; const body = Object.fromEntries(new FormData(event.currentTarget)); try { await api(forms[kind].endpoint, { method: 'POST', body: JSON.stringify(body) }); $('#form-dialog').close(); event.currentTarget.reset(); toast(`${forms[kind].title.replace('Add ', '')} saved.`); await loadData(); } catch (error) { toast(describeError(error), true); } });
$('#run-research').onclick = async () => { const question = $('#research-question').value.trim(); if (!question) return toast('Enter a research question first.', true); const output = $('#research-output'); output.className = 'research-output loading'; output.innerHTML = '<p>Searching current sources and checking the evidence…</p>'; try { const result = await api('/research', { method: 'POST', body: JSON.stringify({ question, opportunityId: $('#research-opportunity').value || undefined }) }); output.className = 'research-output'; output.innerHTML = `<div class="research-meta">CHECKED ${clean(formatDate(result.lastCheckedAt))} · ${clean(result.model)}</div><div>${clean(result.answer)}</div><div class="sources"><strong>Sources</strong>${result.citations.map((source) => `<a href="${clean(source.url)}" target="_blank" rel="noopener">${clean(source.title || source.url)} ↗</a>`).join('') || '<small>No citations were returned. Verify these findings before use.</small>'}</div>`; if ($('#research-opportunity').value) await loadData(); } catch (error) { output.className = 'research-output empty'; output.innerHTML = `<h3>Research failed</h3><p>${clean(describeError(error))}</p>`; } };
$('#upload-button').onclick = () => $('#file-input').click(); $('#file-input').onchange = async (event) => { const file = event.target.files[0]; if (!file) return; if (file.size > 4_300_000) return toast('Please choose a file smaller than 4 MB.', true); const category = /xlsx?|csv/i.test(file.name) ? 'budget' : /pdf|docx?/i.test(file.name) ? 'guidance' : 'other'; const base64 = await new Promise((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1]); reader.readAsDataURL(file); }); try { await api('/files', { method: 'POST', body: JSON.stringify({ filename: file.name, contentType: file.type || 'application/octet-stream', category, base64 }) }); toast(`${file.name} uploaded.`); state.tab = 'files'; $$('[data-tab]').forEach((button) => button.classList.toggle('active', button.dataset.tab === 'files')); await loadData(); } catch (error) { toast(describeError(error), true); } finally { event.target.value = ''; } };
$('#login-form').onsubmit = async (event) => { event.preventDefault(); const button = $('button[type="submit"]', event.currentTarget); const form = Object.fromEntries(new FormData(event.currentTarget)); button.disabled = true; $('#login-error').textContent = ''; try { await api('/auth/login', { method: 'POST', body: JSON.stringify(form) }); location.reload(); } catch (error) { $('#login-error').textContent = error.message; button.disabled = false; } };
$('#profile-button').onclick = async () => { if (state.preview) return; try { await api('/auth/logout', { method: 'POST', body: '{}' }); location.reload(); } catch (error) { toast(describeError(error), true); } };
onAuthChange(() => { if (!state.preview) location.reload(); }); registerWebMCP(); showView(location.hash.slice(1) in { overview:1,pipeline:1,research:1,library:1,activity:1 } ? location.hash.slice(1) : 'overview'); boot();
